[28/May/2014 23:50:09] DEBUG [controlProjects.views:49] Hey there it works!!
[28/May/2014 23:50:09] INFO [controlProjects.views:50] Hey there it works!!
[28/May/2014 23:50:09] WARNING [controlProjects.views:51] Hey there it works!!
[28/May/2014 23:50:09] ERROR [controlProjects.views:52] Hey there it works!!
[28/May/2014 23:50:13] DEBUG [controlProjects.views:49] Hey there it works!!
[28/May/2014 23:50:13] INFO [controlProjects.views:50] Hey there it works!!
[28/May/2014 23:50:13] WARNING [controlProjects.views:51] Hey there it works!!
[28/May/2014 23:50:13] ERROR [controlProjects.views:52] Hey there it works!!
[02/Jul/2014 00:21:51] ERROR [django.request:224] Internal Server Error: /controlProjects/GoalLight/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/stefan/Documents/Aptana_3_Workspace/Goal_Light_Site/controlProjects/views.py", line 26, in goalLight
    goal = GoalLight.objects.get(user = user)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/venv/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: GoalLight matching query does not exist.
[02/Jul/2014 00:22:25] WARNING [django.request:143] Not Found: /static/admin/css/base.css
[02/Jul/2014 00:22:25] WARNING [django.request:143] Not Found: /static/admin/css/login.css
[02/Jul/2014 00:22:29] WARNING [django.request:143] Not Found: /static/admin/css/base.css
[02/Jul/2014 00:22:29] WARNING [django.request:143] Not Found: /static/admin/css/login.css
[02/Jul/2014 00:22:47] WARNING [django.request:143] Not Found: /static/admin/css/base.css
[02/Jul/2014 00:22:47] WARNING [django.request:143] Not Found: /static/admin/css/login.css
[05/Jul/2014 20:29:18] WARNING [django.request:143] Not Found: /favicon.ico
[05/Jul/2014 20:29:18] WARNING [django.request:143] Not Found: /favicon.ico
[05/Jul/2014 20:29:28] ERROR [django.request:224] Internal Server Error: /controlProjects/GoalLight/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/controlProjects/views.py", line 26, in goalLight
    goal = GoalLight.objects.get(user = user)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: GoalLight matching query does not exist.
[05/Jul/2014 20:31:23] DEBUG [controlProjects.views:49] Hey there it works!!
[05/Jul/2014 20:31:23] INFO [controlProjects.views:50] Hey there it works!!
[05/Jul/2014 20:31:23] WARNING [controlProjects.views:51] Hey there it works!!
[05/Jul/2014 20:31:23] ERROR [controlProjects.views:52] Hey there it works!!
[05/Jul/2014 20:31:25] DEBUG [controlProjects.views:49] Hey there it works!!
[05/Jul/2014 20:31:25] INFO [controlProjects.views:50] Hey there it works!!
[05/Jul/2014 20:31:25] WARNING [controlProjects.views:51] Hey there it works!!
[05/Jul/2014 20:31:25] ERROR [controlProjects.views:52] Hey there it works!!
[06/Jul/2014 00:26:17] WARNING [django.request:143] Not Found: /favicon.ico
[06/Jul/2014 00:26:17] WARNING [django.request:143] Not Found: /favicon.ico
[06/Jul/2014 00:26:27] ERROR [django.request:224] Internal Server Error: /login/theLogin/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/login/views.py", line 107, in user_login
    user = authenticate(username=username, password=password)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 83, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 231, in get_columns
    col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 306, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 61, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
[07/Jul/2014 18:28:48] WARNING [django.request:143] Not Found: /favicon.ico
[07/Jul/2014 18:28:48] WARNING [django.request:143] Not Found: /favicon.ico
[07/Jul/2014 18:39:48] ERROR [django.request:224] Internal Server Error: /login/theLogin/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/login/views.py", line 107, in user_login
    user = authenticate(username=username, password=password)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 83, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 231, in get_columns
    col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 306, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 61, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
[07/Jul/2014 18:57:48] ERROR [django.request:224] Internal Server Error: /login/theLogin/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/login/views.py", line 107, in user_login
    user = authenticate(username=username, password=password)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 83, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 231, in get_columns
    col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 306, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 61, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
[07/Jul/2014 19:00:37] DEBUG [controlProjects.views:49] Hey there it works!!
[07/Jul/2014 19:00:37] INFO [controlProjects.views:50] Hey there it works!!
[07/Jul/2014 19:00:37] WARNING [controlProjects.views:51] Hey there it works!!
[07/Jul/2014 19:00:37] ERROR [controlProjects.views:52] Hey there it works!!
[07/Jul/2014 19:00:38] DEBUG [controlProjects.views:49] Hey there it works!!
[07/Jul/2014 19:00:38] INFO [controlProjects.views:50] Hey there it works!!
[07/Jul/2014 19:00:38] WARNING [controlProjects.views:51] Hey there it works!!
[07/Jul/2014 19:00:38] ERROR [controlProjects.views:52] Hey there it works!!
[07/Jul/2014 19:11:02] ERROR [django.request:224] Internal Server Error: /login/theLogin/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/login/views.py", line 107, in user_login
    user = authenticate(username=username, password=password)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 83, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 231, in get_columns
    col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 306, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 61, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
[07/Jul/2014 19:29:33] ERROR [django.request:224] Internal Server Error: /login/theLogin/
Traceback (most recent call last):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/login/views.py", line 107, in user_login
    user = authenticate(username=username, password=password)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
    user = backend.authenticate(**credentials)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 16, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/contrib/auth/models.py", line 167, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 83, in as_sql
    out_cols, s_params = self.get_columns(with_col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 231, in get_columns
    col_aliases)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 306, in get_default_columns
    r = '%s.%s' % (qn(alias), qn2(field.column))
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 61, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/stefan/Documents/Projects/Goal_Light_Site/env/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
